// Single source of truth for HTTP response headers.
//   node scripts/headers.mjs  → writes public/_headers (Netlify, Cloudflare Pages) and vercel.json (Vercel)
// scripts/e2e.mjs imports these too, so the CSP is exercised against the real pages in tests.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

// 'unsafe-inline' for scripts is required by Next.js static export (inline bootstrap/RSC payload; no per-request
// nonce is possible on a static host). Every other directive is locked to same-origin.
export const CSP = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self'",
  "connect-src 'self'",
  "manifest-src 'self'",
  "worker-src 'self'",
  "frame-src 'none'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "upgrade-insecure-requests",
].join("; ");

export const SECURITY_HEADERS = {
  "Content-Security-Policy": CSP,
  "Strict-Transport-Security": "max-age=63072000; includeSubDomains",
  "X-Content-Type-Options": "nosniff",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Permissions-Policy": "camera=(), microphone=(), geolocation=(), payment=(), usb=(), browsing-topics=()",
  "Cross-Origin-Opener-Policy": "same-origin",
  "X-Frame-Options": "DENY",
};

export const CACHE_RULES = [
  // Content-hashed build output: cache forever.
  { source: "/_next/static/*", vercel: "/_next/static/(.*)", value: "public, max-age=31536000, immutable" },
  // Generated photos are named by slot, not content hash: cache for a week, revalidate in the background.
  { source: "/images/generated/*", vercel: "/images/generated/(.*)", value: "public, max-age=604800, stale-while-revalidate=86400" },
];

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const block = (path, headers) => [path, ...Object.entries(headers).map(([k, v]) => `  ${k}: ${v}`)].join("\n");
  writeFileSync(
    "public/_headers",
    [
      "# Generated by scripts/headers.mjs — edit there.",
      block("/*", SECURITY_HEADERS),
      ...CACHE_RULES.map((r) => block(r.source, { "Cache-Control": r.value })),
    ].join("\n\n") + "\n",
  );
  const vercel = {
    $schema: "https://openapi.vercel.sh/vercel.json",
    trailingSlash: true,
    headers: [
      { source: "/(.*)", headers: Object.entries(SECURITY_HEADERS).map(([key, value]) => ({ key, value })) },
      ...CACHE_RULES.map((r) => ({ source: r.vercel, headers: [{ key: "Cache-Control", value: r.value }] })),
    ],
  };
  writeFileSync("vercel.json", JSON.stringify(vercel, null, 2) + "\n");
  console.log("wrote public/_headers and vercel.json");
}
